version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: api-rest-node
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:latest
    container_name: api-rest-node-test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - ./.postgres-test-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
  .postgres-test-data:
